// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnr60hDXCwGAdx3zqGJkJUHdsKstecpmw',
    appId: '1:644557759584:web:d38db83d5e02e5f6cc0f05',
    messagingSenderId: '644557759584',
    projectId: 'shope-c0417',
    authDomain: 'shope-c0417.firebaseapp.com',
    storageBucket: 'shope-c0417.firebasestorage.app',
    measurementId: 'G-XLFTMRWZCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_uO2jPmmm_JWBMthR1BOzVxr0HlcbCqc',
    appId: '1:644557759584:android:029b3acd15fb2eeccc0f05',
    messagingSenderId: '644557759584',
    projectId: 'shope-c0417',
    storageBucket: 'shope-c0417.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2eRLRh4pf3IgbXWmGqIWcR0MRZLrflts',
    appId: '1:644557759584:ios:fdaee219bb036f1acc0f05',
    messagingSenderId: '644557759584',
    projectId: 'shope-c0417',
    storageBucket: 'shope-c0417.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2eRLRh4pf3IgbXWmGqIWcR0MRZLrflts',
    appId: '1:644557759584:ios:fdaee219bb036f1acc0f05',
    messagingSenderId: '644557759584',
    projectId: 'shope-c0417',
    storageBucket: 'shope-c0417.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnr60hDXCwGAdx3zqGJkJUHdsKstecpmw',
    appId: '1:644557759584:web:1b4be3640f677b72cc0f05',
    messagingSenderId: '644557759584',
    projectId: 'shope-c0417',
    authDomain: 'shope-c0417.firebaseapp.com',
    storageBucket: 'shope-c0417.firebasestorage.app',
    measurementId: 'G-NW94MBK6B3',
  );
}
